/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as RoadmapsIndexRouteImport } from './routes/roadmaps.index'
import { Route as TopicsSlugRouteImport } from './routes/topics.$slug'
import { Route as RoadmapsSlugRouteImport } from './routes/roadmaps.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsIndexRoute = RoadmapsIndexRouteImport.update({
  id: '/roadmaps/',
  path: '/roadmaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsSlugRoute = RoadmapsSlugRouteImport.update({
  id: '/roadmaps/$slug',
  path: '/roadmaps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/roadmaps': typeof RoadmapsIndexRoute
  '/topics': typeof TopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timeline': typeof TimelineRoute
  '/roadmaps/$slug': typeof RoadmapsSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/roadmaps/': typeof RoadmapsIndexRoute
  '/topics/': typeof TopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/sitemap.xml'
    | '/timeline'
    | '/roadmaps/$slug'
    | '/topics/$slug'
    | '/roadmaps/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/sitemap.xml'
    | '/timeline'
    | '/roadmaps/$slug'
    | '/topics/$slug'
    | '/roadmaps'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/glossary'
    | '/sitemap.xml'
    | '/timeline'
    | '/roadmaps/$slug'
    | '/topics/$slug'
    | '/roadmaps/'
    | '/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlossaryRoute: typeof GlossaryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimelineRoute: typeof TimelineRoute
  RoadmapsSlugRoute: typeof RoadmapsSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  RoadmapsIndexRoute: typeof RoadmapsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/': {
      id: '/roadmaps/'
      path: '/roadmaps'
      fullPath: '/roadmaps/'
      preLoaderRoute: typeof RoadmapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps/$slug': {
      id: '/roadmaps/$slug'
      path: '/roadmaps/$slug'
      fullPath: '/roadmaps/$slug'
      preLoaderRoute: typeof RoadmapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlossaryRoute: GlossaryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimelineRoute: TimelineRoute,
  RoadmapsSlugRoute: RoadmapsSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  RoadmapsIndexRoute: RoadmapsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
